### ISSUE TITLE
Issue  list table exceeds 100,000

### ISSUE THREAD

**Issue by BioInfrookie** [broadinstitute/rigerj#20]
Hello, I've encountered a problem where the number of rows in my list table exceeds 100,000. How can I resolve this issue? Thank you for your assistance.

`$java -jar /home/qzh/software/rigerj/target/rigerj-2.0.3-assembly.jar -scoringMethod SecondBestRank -inputFile Merge_sgRNA_fold_rank.txt -outputFile tmp
Exception in thread "main" java.lang.NumberFormatException: For input string: "1e+05"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.<init>(Integer.java:867)
        at org.broadinstitute.gpp.rigerj.RigerJMain.createHairpinDatas(RigerJMain.java:202)
        at org.broadinstitute.gpp.rigerj.RigerJMain.buildRigerInputs(RigerJMain.java:156)
        at org.broadinstitute.gpp.rigerj.RigerJMain.runRigerJ(RigerJMain.java:143)
        at org.broadinstitute.gpp.rigerj.RigerJMain.main(RigerJMain.java:57)
`

**Comment by BioInfrookie** [comment]
`$ cat Merge_sgRNA_fold_rank.txt | wc -l
100001
`

**Comment by tmgreen** [comment]
Thanks for bringing this to our attention.  I've put in a pull request to fix it: https://github.com/broadinstitute/rigerj/pull/21

**Comment by tmgreen** [comment]
This is fixed in release 2.0.3: https://github.com/broadinstitute/rigerj/releases/tag/2.0.3

**Comment by tmgreen** [comment]
@BioInfrookie I'm briefly reopening this issue because, while we fixed that particular bug, you are probably not going to have great results in the end if the rank column in your input file contains scientific notation with so few significant figures.   Unless you really know what you're doing, I'd advise you to take a look at whatever is generating your input file and see if you can have it produce exact integers.

**Comment by BioInfrookie** [comment]
> Thanks for bringing this to our attention. I've put in a pull request to fix it: #21

You're welcome for paying attention to this issue and helping me resolve the doubt.

**Comment by BioInfrookie** [comment]
> @BioInfrookie I'm briefly reopening this issue because, while we fixed that particular bug, you are probably not going to have great results in the end if the rank column in your input file contains scientific notation with so few significant figures. Unless you really know what you're doing, I'd advise you to take a look at whatever is generating your input file and see if you can have it produce exact integers.

Understood, I conducted a Cas9 screening experiment, designing 6 sgRNAs for each gene, covering 99% of the gene information. Before calculating the p-value, I performed a quality screening to remove low-quality sgRNAs, but even so, the number of rows still exceeded 100,000, which is why I encountered this issue. I will check my input file again.
I have to admire the program you've written.

**Comment by tmgreen** [comment]
Thanks and good luck!
